name: $(Build.BuildId)

trigger:
  branches:
    include:
      - main
      - sprint2

variables:
  buildConfiguration: 'Release'
  dotNetVersion: '8.0.x'

pool:
  name: MyCustomPool
  demands:
    - Agent.OS -equals Windows_NT

steps:
- task: UseDotNet@2
  displayName: 'Install .NET 8'
  inputs:
    version: $(dotNetVersion)

- task: DotNetCoreCLI@2
  displayName: 'Restore Packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build Solution'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish Web App'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'webapp'
    publishLocation: 'pipeline'